# Site settings
title: Andessen Blog
email: (To be added soon)
description: > # this means to ignore newlines until "baseurl:"
	Data science, startup tech, coding, mathematics.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: andersjalan
github_username:  andessen

# Build settings
markdown: kramdown
