title: Andessen Blog
email: (To be added soon)
description: > # this means to ignore newlines until "baseurl:"
	Data science, startup tech, coding, mathematics.
baseurl: /blog 
url: "http://yourdomain.com" 
twitter_username: andersjalan
github_username:  andessen
markdown: kramdown
