title: "Andessen Blog"
email: "(To be added soon)"
description: "Data science, startup tech, coding, mathematics"
baseurl: /blog 
url: "http://yourdomain.com" 
twitter_username: andersjalan
github_username:  andessen
markdown: kramdown
